### PR TITLE
Doc Gen Tool Generates Unrestricted Items

### LINKED ISSUE #1998: Docs Generation Does Not Include Unrestricted Items
The docs generation tool does not generate docs for library items listed as `@Config(Unrestricted)`. These items should be included in the docs generation and the table of contents.

### PR DESCRIPTION
**Pull request by ScottCarda-MS**
This fixes #1998. This also updates the table of contents to put Unstable namespaces at the end.

### CODE REVIEW

**Comment by minestarks** [comment]
@ScottCarda-MS  what about `@Config(Base)` / `Config(Adaptive)` items? Are we intentionally excluding them now? 

(Acknowledging that exposing _all_ configurations sounds difficult, given the current design of conditional compilation. So a compromise may be needed here).

**Comment by ScottCarda-MS** [comment]
> @ScottCarda-MS what about `@Config(Base)` / `Config(Adaptive)` items? Are we intentionally excluding them now?
> 
> (Acknowledging that exposing _all_ configurations sounds difficult, given the current design of conditional compilation. So a compromise may be needed here).

This should include all items, including Base and Adaptive. I added a test for finding the Adaptive `Std.Intrinsic.AND` operation. I couldn't find any Base items in our library to test against.

**Comment by minestarks** [comment]
@ScottCarda-MS 
But `AND` has a `@Config(not Adaptive)` implementation as well, are you sure that's not the one you're getting?

```qsharp
@Config(not Adaptive)
operation AND(control1 : Qubit, control2 : Qubit, target : Qubit) : Unit is Adj {
    PhaseCCX(control1, control2, target);
}
```

Would doc generation work for items that have a `Adaptive`/`Base` implementation and nothing else?

**Comment by DragosDanielBoia** [comment]
@microsoft-github-policy-service agree

**Comment by DragosDanielBoia** [comment]
@microsoft-github-policy-service rerun

**Comment by ScottCarda-MS** [comment]
> Would doc generation work for items that have a `Adaptive`/`Base` implementation and nothing else?

I'm not able to tell at this point as there is no such content in the existing library code. Trying to update the libraries to include such code is running into issues. I'm going to save this for a future PR if/when we add such content to the libraries.

Since the existing test doesn't determine what I thought it did (as you pointed out, AND has both an Adaptive and not Adaptive definition), I'm removing the test.

**Comment by ScottCarda-MS** [comment]
Closing in favor of #2012

**Pull request closed without merging**
