### PR TITLE
Switch from deprecated `checkCode` to `update_document` from the language service in `basics.js`.

### LINKED ISSUE #469: Switch from deprecated `checkCode` to `update_document` from the language service in `basics.js`.
In `basics.js`, we currently use a deprecated test function. We should move off of it.

### PR DESCRIPTION
**Pull request by swernli**
Fixes #469

### CODE REVIEW

**Comment by billti** [comment]
Do we still have coverage for that API anywhere, being that's what QCOM is still using currently. If we are removing it, we'll need to document migration steps for them. I believe the plan was they should move first, then we'll remove it after.

**Comment by swernli** [comment]
> Do we still have coverage for that API anywhere, being that's what QCOM is still using currently. If we are removing it, we'll need to document migration steps for them. I believe the plan was they should move first, then we'll remove it after.

The API hasn't been removed, so we aren't breaking anyone yet. The `checkCode` implementation already just wraps calls into the language server, so the only special thing it does is map positions in the returned diagnostics with `mapUtf8UnitsToUtf16Units`. Do we want coverage specifically for that? Because the previous tests really didn't verify any corner cases of that mapping.

**Comment by billti** [comment]
If QCOM is still using checkCode, (which arguably gets a lot more usage than our VS Code extension currently), then I think we should still have the tests exercise checkCode.

**Comment by swernli** [comment]
In that case, I'll drop this for now.

**Pull request closed without merging**
