### PR TITLE
Fix GetLink-Tutorial-Playground-state issue 1558

### PR DESCRIPTION
**Pull request by ggridin**
This PR closes https://github.com/microsoft/qsharp/issues/1558

Included changes:
1. props.linkedCode must be reset after nav click.
2. Only "code" and "profile" URL params are reset, instead of all URL params (which is better practice). WebAPI is used instead of string operations.

### CODE REVIEW

**Comment by ggridin** [comment]
Testing done:
1. Original use case
    - Open clean playground state.
    - Make some noticeable changes to the default code.
    - Click the "Get a link to this code" button. (notice the URL changes)
    - Refresh the page using the browser refresh button.
    - Click on one of the Tutorial links. (notice how the URL resets.)
 
2. Modified original use case
    - Open clean playground state.
    - Make some noticeable changes to the default code.
    - Click the "Get a link to this code" button. (notice the URL changes)
    - Load the new URL
    - Optionally: refresh the page using the browser refresh button.
    - Click on one of the Tutorial links. (notice how the URL resets.)
 
 3. Original use case for Samples
 
 4. Original use case with logLevel in URL. Make sure that additional parameter is not removed/overwritten
    - Open clean playground state.
    - Add "logLevel=info" to URL: http://localhost:5555/?logLevel=info
    - Make some noticeable changes to the default code.
    - Click the "Get a link to this code" button. (notice the URL changes)
    - Refresh the page using the browser refresh button.
    - Click on one of the Tutorial links. (notice how the URL resets.)
    
5. Get link on the linked code
    - Open clean playground state.
    - Make some noticeable changes to the default code.
    - Click the "Get a link to this code" button. (notice the URL changes)
    - Load the new URL
    - Make some noticeable changes to the loaded code.
    - Click the "Get a link to this code" button. (notice the URL changes)
    - Load the new URL, make sure that the URL is correct (no multiple "code" params) and the right code is loaded
    - Click on one of the Tutorial links. (notice how the URL resets.)

6. Load two tabs with different linked code and make sure that they do not impact each other.

**Comment by ggridin** [comment]
@billti @cesarzc @minestarks could you review the changes?

**Comment by ggridin** [comment]
@swernli @tcNickolas is it possible to review this PR ?

**Review by swernli — APPROVED** [review]

**Review by cesarzc — APPROVED** [review]
Thank you for this fix!

**Pull request merged**
